kakao:
  client-id: ${KAKAO_CLIENT_ID:951729b2838c2c5c32db85458d1cbdc5}
  client-secret: ${KAKAO_CLIENT_SECRET:G0OaayJip0SkT0qRhLKkEGTFtQZvtUjn}
  redirect-uri: http://localhost:7003/user/kakao/kakaoCallback
  kauth-host: https://kauth.kakao.com
  kapi-host: https://kapi.kakao.com

naver:
  client_secret: ${NAVER_CLIENT_SECRET:2sAH6nEq3y}
  client-id: ${NAVER_CLIENT_ID:jkkYoO0HihnD9w7fZALc}
  redirect_uri: http://localhost:7003/user/naver/naverCallback
  nauth-host: https://nid.naver.com
  napi-host: https://openapi.naver.com

portone:
  api-key: ${PORTONE_API_KEY:5014357720785836}
  api-secret: ${PORTONE_API_SECRET:SPr43WRyb2SQ8whuWs20tSr54WH14kr2pxTUIpMGa6EdJddgGhdjS826zQVP97s0XqWEUXxcajFhCKIc}