spring:
  application:
    name: HouseholdAccount
  profiles:
    include: API-KEY
  datasource:
#    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1dd
    url: jdbc:oracle:thin:@//192.168.0.7:1521/XEPDB1
    username: smaccount
    password: smaccountpw
  jpa:
        show-sql: true
        properties:
          hibernate:
            format_sql: true
            highlight_sql: true

server:
  port: 7003
