spring:
  application:
    name: HouseholdAccount
  profiles:
    active: dev       # ← 테스트용 프로필 활성화 실제적용시 지우거나 prod 로 바꾸면됨
    include: API-KEY
  datasource:
#    url: jdbc:oracle:thin:@//localhost:2345/XEPDB1
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    username: smaccount
    password: smaccountpw
  jpa:
        show-sql: true
        properties:
          hibernate:
            format_sql: true
            highlight_sql: true

server:
  port: 7003

render:
  render-host: https://mmml-deep-learning-server.onrender.com/