spring:
  application:
    name: HouseholdAccount
  profiles:
    include: API-KEY
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    username: scott
    password: tiger
  jpa:
        show-sql: true
        properties:
          hibernate:
            format_sql: true
            highlight_sql: true

server:
  port: 7003